=== JaMachine/JDome/src/NewXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.jamachine.com/ja"
	xmlns:tns="http://www.jamachine.com/ja">

	<element name="allTarifs">
		<complexType>
			<sequence>
				<element name="tarif" type="tns:tariftype" minOccurs="0"
					maxOccurs="unbounded">
				</element>
			</sequence>
		</complexType>
	</element>
	<complexType name="tariftype">
		<sequence>
			<element name="name" type="string" minOccurs="0" maxOccurs="55"></element>
			<element name="operatorName" type="string" minOccurs="0"
				maxOccurs="55"></element>
			<element name="payrol" type="integer" minOccurs="0"
				maxOccurs="unbounded"></element>
			<element name="callPrices" type="tns:callPrices">
			</element>
			<element name="sms" type="integer" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="parametrs" type="tns:parametrs"></element>

		</sequence>
	</complexType>
	<complexType name="callPrices">
		<sequence>
			<element name="inside" type="integer" minOccurs="0"
				maxOccurs="unbounded"></element>
			<element name="outcide" type="integer" minOccurs="0"
				maxOccurs="unbounded"></element>
			<element name="city" type="integer" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>
	<complexType name="parametrs">
		<sequence>
			<element name="favoriteNumbers" type="integer" minOccurs="0"
				maxOccurs="unbounded"></element>
			<element name="tarification" type="integer" minOccurs="1"
				maxOccurs="12"></element>
			<element name="conectionPrice" type="integer" minOccurs="0"
				maxOccurs="unbounded"></element>
		</sequence>
	</complexType>
</schema>

=== JaMachine/JDome/src/NewFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:allTarifs xmlns:tns="http://www.jamachine.com/ja"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.jamachine.com/ja NewXMLSchema.xsd">
	<tarif>
		<name>free</name>
		<operatorName>Best Mobil</operatorName>
		<payrol>0</payrol>
		<callPrices>
			<inside>0</inside>
			<outcide>15</outcide>
			<city>20</city>
		</callPrices>
		<sms>1</sms>
		<parametrs>
			<favoriteNumbers>5</favoriteNumbers>
			<tarification>1</tarification>
			<conectionPrice>1</conectionPrice>
		</parametrs>
	</tarif>
	<tarif>
		<name>expensive</name>
		<operatorName>kyivstar</operatorName>
		<payrol>55</payrol>
		<callPrices>
			<inside>0</inside>
			<outcide>25</outcide>
			<city>25</city>
		</callPrices>
		<sms>5</sms>
		<parametrs>
			<favoriteNumbers>10</favoriteNumbers>
			<tarification>1</tarification>
			<conectionPrice>2</conectionPrice>
		</parametrs>
	</tarif>
</tns:allTarifs>
